### ISSUE TITLE
config strings not starting with core name

### ISSUE THREAD

**Issue by Tartifless** [vircon32/vircon32-libretro#15]
Hello,

Currently the the frameskip option is simply called "enable_frameskip" in the rectroarch core configuration file, would it be possible to adapt the naming convention other cores use and add the core name before the option string ?

CURRENT BEHAVIOR:
emuscv_palette = "AUTO"
emuscv_pixelaspect = "AUTO"
emuscv_resolution = "AUTO"
**enable_frameskip = "Enabled"**
fba-allow-depth-32 = "disabled"
fba-analog-speed = "10"
fba-cpu-speed-adjust = "100"
fba-diagnostic-input = "None"
fba-dipswitch-garou-Autofire = "(Default) Off"

REQUEST:
emuscv_palette = "AUTO"
emuscv_pixelaspect = "AUTO"
emuscv_resolution = "AUTO"
**vircon32_enable_frameskip = "Enabled"**
fba-allow-depth-32 = "disabled"
fba-analog-speed = "10"
fba-cpu-speed-adjust = "100"
fba-diagnostic-input = "None"
fba-dipswitch-garou-Autofire = "(Default) Off"

**Comment by vircon32** [comment]
Hi, I see no problem to change that name. Sorry, I was not aware of this convention. I just pushed this change, the name is now vircon32_enable_frameskip. If you need new binaries they will be available from the libretro buildbot triggers a new build after the change (usually takes 1-2 hours to finish all build binaries).

**Comment by Tartifless** [comment]
Thanks a lot , that was super fast !

**Comment by vircon32** [comment]
Thank you! Well this was quick to do but yes, things won't always be this fast...
Since this is done I'll close the issue.
