### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by gouchi** [vircon32/vircon32-libretro#3]
Hi,

Will it possible to add a [LICENSE](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) for the repository ?

Thank you.

Kind regards,

**Comment by vircon32** [comment]
Hi gouchi. Yes, this was missing a license file. I just added it (license is FreeBSD), so I will close this. Thank you.
