### ISSUE TITLE
Built EmuELEC core for Vircon32

### ISSUE THREAD

**Issue by Chandler-Kluser** [vircon32/vircon32-libretro#6]
I was fully able to compile and run Vircon32 libretro core (and its games) in these arm64 cheap tv boxes (actually in a Amlogic x905x3 device).

I will sanitize the code and make soon a PR in this repository and in EmuELEC in order to make the new builds to have Vircon32 core.

If someone just want to try the built shared object itself you can download through [this link](https://github.com/vircon32/vircon32-libretro/files/12555305/vircon32_libretro.zip).

To run the core, just unzip the file and place it into `cores` folder, and paste the BIOS file into `bios` folder.

**Comment by vircon32** [comment]
Thank you, Chandler! It is cool that we have Vircon32 available in more systems :) I just fixed a small build error under non Emuelec systems and did a couple of formatting changes. Your PR is now merged, so I guess I will close this issue as well.
